version: '3'
services:
  fpm70:
    build:
        context: ./nginx
        dockerfile: Dockerfile.php70
    volumes:
      - ./magento/nginx70:/var/www/html
    networks:
      - webnet

  nginx70:
    image: nginx
    ports:
      - 8700-8709:80-89
    volumes:
      - ./magento/nginx70:/var/www/html
      - ./nginx/default.php70.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet
